### ISSUE TITLE
Create "meta codec" for serializing transactions

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#115]
Scope: iov-write

We want to be able to add new transaction formats for blockchains, without requiring that all the code goes into web4 (with PRs) and must be published and updated on all clients... We also don't want to allow plugins of arbitrary code in web4-write, as it has access to the keys and is very sensitive.

Up to know, we define a custom code for each chain. Following #114, we now want to abstract that into "meta-codec" for serializing transactions that works for a "blockchain family". Thus we could use the weave format and sign byte calculations with dynamically loaded protobuf defintions, and then use that for bcp-demo, bns, and any other weave-based chain. We could set a list of contracts and APIs for the ethereum family and allow the same "meta-codec" to generate implementations pointing to specific contracts on eg. Rinkeby, ETH, and ETC.

- [ ] Define format for weave-based chains and implement "meta-codec"
- [ ] Add any "meta" into lisk based codec
- [ ] Define format (using standard eth tools) and define "meta-codec" for all ethereum/web3/rlp chains
- [ ] Test this is compatible with current bcp/bns implementation
- [ ] Add type-safety for bcp-basic and bns queries

This is maybe many issues, definitely many, many PRs

**Comment by webmaster128** [comment]
Closing as mostly outdated. There is currently no plan for a meta-codec. Transaction type registration is now implemented in a decentralized fashion.
