### ISSUE TITLE
Meta: Remove transaction creator

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1328]
This is an overview ticket for multiple steps that have the goal to remove the transaction creator.

- [x] Make signing identity explicit in UserProfile.signTransaction #1308
- [x] Add signing identity to signAndPost RPC call #1315
- [x] Refactor `codec.bytesToSign` to accept an unsigned transaction without a creator #1314
- [x] Adapt READMEs to creator change #1331
- [x] Fix deploy_proposals.js after creator change #1332
- [x] Remove concept of `primarySignature` from transactions #1334

**Comment by willclarktech** [comment]
@webmaster128 Anything else that should go in here?

**Comment by webmaster128** [comment]
Very good question. I don't see anything right now but want to look at it again tomorrow.
